#!/usr/bin/env python3
"""Fold generated text into an issue body without destroying what was there.

Reads the current body from CURRENT and the generated text from GENERATED, then
writes the merged result to MERGED. Any previous block between the markers is
replaced, so re-applying a label refreshes the summary instead of stacking
copies of it.
"""

import os
import pathlib
import re
import sys

START = "<!-- ai-summary:start -->"
END = "<!-- ai-summary:end -->"
HEADING = "**Automated summary**, generated by GitHub Copilot. It can be wrong."

# GitHub rejects issue bodies beyond this length.
BODY_LIMIT = 65536

current = pathlib.Path(os.environ["CURRENT"]).read_text(encoding="utf-8")
generated = pathlib.Path(os.environ["GENERATED"]).read_text(encoding="utf-8").strip()
merged_path = pathlib.Path(os.environ["MERGED"])

if not generated:
    print("::error::Generated text is empty, refusing to edit the issue body.")
    sys.exit(1)

stripped = re.sub(
    re.escape(START) + r".*?" + re.escape(END), "", current, flags=re.DOTALL
).rstrip()

block = f"{START}\n{HEADING}\n\n{generated}\n{END}"
merged = f"{stripped}\n\n{block}\n" if stripped else f"{block}\n"

if len(merged) > BODY_LIMIT:
    print(
        f"::error::Merged body would be {len(merged)} characters, over the "
        f"{BODY_LIMIT} limit. Leaving the issue body alone."
    )
    sys.exit(1)

merged_path.write_text(merged, encoding="utf-8")
print(f"Merged body is {len(merged)} characters (was {len(current)}).")
